import descriptionPolicy from "../../data/reference/description-policy.json" with { type: "json" };

// Formats and presentation metadata. Account permissions are selected separately.
export const CANONICAL_PRODUCER_HEADER = [
  "slug",
  "nombre",
  "municipio",
  "categoria",
  "productos estrella",
  "direccion",
  "descripcion",
  "horario",
  "telefono",
  "correo",
  "web",
  "Facebook",
  "Instagram",
  "Google Maps",
  "lat",
  "lon",
  "imagen",
  "verificacion",
  "Venta online",
  "Canal de venta",
  "categorias adicionales",
  "producer_id",
  "descripcion_locale",
  "visitas guiadas",
  "mensaje a la comunidad",
  "mensaje_comunidad_locale",
  "enlace destacado 1",
  "enlace destacado 2",
  "country",
  "region",
  "area",
  "video",
  "quien hay detras",
  "quien_hay_detras_locale",
  "historia",
  "historia_locale",
  "fecha ultimo cambio",
] as const;

export const ONLINE_SALES_VALUES = ["sí", "no", "no comprobado"] as const;
export const SALES_CHANNEL_VALUES = [
  "ecommerce",
  "whatsapp",
  "email",
  "telefono",
  "suscripcion",
  "marketplace",
] as const;
export const PRODUCER_BEHIND_MAX_CHARACTERS = 2_000;
export const PRODUCER_HISTORY_MAX_CHARACTERS = 4_000;
export const PRODUCER_LAST_APPROVED_CHANGE_DATE_FIELD =
  "fecha ultimo cambio" as const;

export const PRODUCER_STANDARD_FIELD_DEFINITIONS = [
  {
    key: "nombre",
    label: "Public name",
    kind: "text",
    required: true,
    maxLength: 160,
    help: "The public producer or brand name.",
  },
  {
    key: "municipio",
    label: "Municipality",
    kind: "text",
    required: true,
    maxLength: 160,
    help: "Municipality of the productive unit, not a sales office.",
  },
  {
    key: "categoria",
    label: "Primary category",
    kind: "category",
    required: true,
    maxLength: 80,
    help: "The producer's main material output.",
  },
  {
    key: "categorias adicionales",
    label: "Additional categories",
    kind: "categories",
    required: false,
    maxLength: 500,
    help: "Other material outputs made by this same productive unit.",
  },
  {
    key: "productos estrella",
    label: "Featured products",
    kind: "textarea",
    required: false,
    maxLength: 500,
    help: "A short list of concrete products, brands or appellations.",
  },
  {
    key: "descripcion",
    label: "Description",
    kind: "textarea",
    required: false,
    maxLength: descriptionPolicy.canonicalMaxCharacters,
    help: "Factual producer-specific information, without promotional claims.",
  },
  {
    key: "descripcion_locale",
    label: "Description language",
    kind: "description-locale",
    required: false,
    maxLength: 3,
    help: "The source language of the canonical description; leave empty only with an empty description.",
  },
  {
    key: "direccion",
    label: "Address",
    kind: "text",
    required: false,
    maxLength: 500,
    help: "Address of the productive unit or producer-facing premises.",
  },
  {
    key: "horario",
    label: "Public hours",
    kind: "textarea",
    required: false,
    maxLength: 1_000,
    help: "Current visiting, collection or public-opening hours.",
  },
  {
    key: "telefono",
    label: "Phone",
    kind: "tel",
    required: false,
    maxLength: 16,
    help: "International E.164 format, for example +34600112233.",
  },
  {
    key: "correo",
    label: "Public email",
    kind: "email",
    required: false,
    maxLength: 254,
    help: "A public contact address for this producer.",
  },
  {
    key: "web",
    label: "Website",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "Official HTTP(S) producer website.",
  },
  {
    key: "Facebook",
    label: "Facebook",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "Official Facebook page URL.",
  },
  {
    key: "Instagram",
    label: "Instagram",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "Official Instagram profile URL.",
  },
  {
    key: "Google Maps",
    label: "Google Maps",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "Reviewed Google Maps listing for the productive unit.",
  },
  {
    key: "lat",
    label: "Latitude",
    kind: "coordinate",
    required: false,
    maxLength: 32,
    help: "WGS84 decimal latitude. Latitude and longitude must be supplied together.",
  },
  {
    key: "lon",
    label: "Longitude",
    kind: "coordinate",
    required: false,
    maxLength: 32,
    help: "WGS84 decimal longitude. Latitude and longitude must be supplied together.",
  },
  {
    key: "Venta online",
    label: "Online sales",
    kind: "online-sales",
    required: true,
    maxLength: 20,
    help: "Whether a current ordering mechanism has been reviewed.",
  },
  {
    key: "Canal de venta",
    label: "Sales channels",
    kind: "sales-channels",
    required: false,
    maxLength: 200,
    help: "Current demonstrated ordering mechanisms.",
  },
] as const;

export const PRODUCER_EXPANDED_FIELD_DEFINITIONS = [
  {
    key: "video",
    label: "Video",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "An official HTTPS YouTube URL for one public producer video.",
  },
  {
    key: "visitas guiadas",
    label: "Guided visits",
    kind: "yes-no",
    required: false,
    maxLength: 2,
    help: "Whether this producer currently offers guided visits; leave empty when unpublished.",
  },
  {
    key: "mensaje a la comunidad",
    label: "Message to the community",
    kind: "textarea",
    required: false,
    maxLength: 1_000,
    help: "A producer-authored public message, preserved in its original language and reviewed before publication.",
  },
  {
    key: "mensaje_comunidad_locale",
    label: "Community message language",
    kind: "description-locale",
    required: false,
    maxLength: 3,
    help: "The source language of the community message; leave empty only when the message is empty.",
  },
  {
    key: "quien hay detras",
    label: "Who is behind the producer",
    kind: "textarea",
    required: false,
    maxLength: PRODUCER_BEHIND_MAX_CHARACTERS,
    help: "Reviewed producer-authored text about the owners or team behind this productive unit.",
  },
  {
    key: "quien_hay_detras_locale",
    label: "Who-is-behind language",
    kind: "description-locale",
    required: false,
    maxLength: 3,
    help: "The source language of the who-is-behind text; leave empty only when that text is empty.",
  },
  {
    key: "historia",
    label: "History",
    kind: "textarea",
    required: false,
    maxLength: PRODUCER_HISTORY_MAX_CHARACTERS,
    help: "Reviewed producer-authored text about the origins and development of this productive unit.",
  },
  {
    key: "historia_locale",
    label: "History language",
    kind: "description-locale",
    required: false,
    maxLength: 3,
    help: "The source language of the history; leave empty only when the history is empty.",
  },
  {
    key: "enlace destacado 1",
    label: "Highlighted link 1",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "A relevant HTTP(S) article, interview or other public page about this producer.",
  },
  {
    key: "enlace destacado 2",
    label: "Highlighted link 2",
    kind: "url",
    required: false,
    maxLength: 2_048,
    help: "A second distinct public HTTP(S) page; link 1 must be filled first.",
  },
] as const;

export const TRANSLATABLE_FIELD_SPECS = [
  {
    field: "descripcion",
    localeField: "descripcion_locale",
    canonicalMaxCharacters: descriptionPolicy.canonicalMaxCharacters,
    translatedMaxCharacters: descriptionPolicy.translatedMaxCharacters,
  },
  {
    field: "quien hay detras",
    localeField: "quien_hay_detras_locale",
    canonicalMaxCharacters: PRODUCER_BEHIND_MAX_CHARACTERS,
    translatedMaxCharacters: 2500,
  },
  {
    field: "historia",
    localeField: "historia_locale",
    canonicalMaxCharacters: PRODUCER_HISTORY_MAX_CHARACTERS,
    translatedMaxCharacters: 5000,
  },
] as const;
